run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - gofmt
    - revive  # replaces golint
    - govet
    - ineffassign
    - misspell
    - unused  # replaces deadcode, varcheck, structcheck
    - typecheck
    - gosimple
    - staticcheck
    - errcheck
    - gosec
    - unconvert
    - goconst
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 10
  revive:
    min-confidence: 0.8
  goconst:
    min-len: 3
    min-occurrences: 2

issues:
  exclude-use-default: false
  exclude:
    # Ignore error handling in tests
    - "error return value not checked.*test"
    # Ignore missing comments for exported functions in tests
    - "exported function.*should have comment.*_test.go"
  exclude-rules:
    # Disable some linters for test files
    - path: _test\.go
      linters:
        - gosec
        - goconst