version: '3.8'

services:
  url-shortener:
    image: ${DOCKER_IMAGE:-ghcr.io/rusik69/url-shortener:latest}
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/url_shortener?sslmode=disable
    depends_on:
      - db
    networks:
      - url-shortener-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/url_shortener_test?sslmode=disable
    networks:
      - url-shortener-network
    depends_on:
      - db
    profiles:
      - test

volumes:
  postgres_data:

networks:
  url-shortener-network:
    driver: bridge
