version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - url-shortener
    networks:
      - url-shortener-network
    restart: unless-stopped

  url-shortener:
    image: ${DOCKER_IMAGE:-ghcr.io/rusik69/url-shortener:latest}
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/url_shortener?sslmode=disable
    depends_on:
      - db
    networks:
      - url-shortener-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # For manual backups if needed
      - postgres_backups:/var/lib/postgresql/backups
    networks:
      - url-shortener-network
    restart: unless-stopped
    # Ensure proper shutdown to prevent data corruption
    stop_grace_period: 30s

volumes:
  postgres_data:
    external: true
    name: shortener_postgres_data
  postgres_backups:

networks:
  url-shortener-network:
    driver: bridge