name: Shortener Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shortener-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Build Shortener
      run: |
        go build -v ./...
      working-directory: shortener

    - name: Run Shortener Tests
      run: |
        go test -v ./...
      working-directory: shortener

    - name: Build Shortener Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/url-shortener:latest .
      working-directory: shortener

    - name: Push Shortener to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_REGISTRY }}/url-shortener:latest
      working-directory: shortener
