name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Build
      run: |
        go build -v ./...

    - name: Run tests
      run: |
        go test -v ./...

    - name: Build Docker image
      run: |
        docker build -t url-shortener:latest .
      working-directory: url-shortener

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag url-shortener:latest ${{ secrets.DOCKER_REGISTRY }}/url-shortener:latest
        docker push ${{ secrets.DOCKER_REGISTRY }}/url-shortener:latest
      working-directory: url-shortener
