name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Start test services
      run: docker compose up -d db
      working-directory: shortener

    - name: Wait for database
      run: |
        timeout 30s bash -c 'until docker compose exec db pg_isready -U postgres; do sleep 1; done'
      working-directory: shortener

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod download
      working-directory: shortener

    - name: Run tests
      run: make test
      working-directory: shortener
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/url_shortener?sslmode=disable

    - name: Run lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: shortener

    - name: Stop test services
      if: always()
      run: docker compose down
      working-directory: shortener

  build:
    name: Build and Push Image
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository_owner }}/url-shortener:latest .
      working-directory: shortener

    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository_owner }}/url-shortener:latest
      working-directory: shortener

  deploy:
    name: Deploy to Production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        if [ -n "${{ secrets.VPSHOST }}" ]; then
          ssh-keyscan -t rsa,ed25519 ${{ secrets.VPSHOST }} >> ~/.ssh/known_hosts 2>/dev/null || true
          # Also add strict host key checking disable as fallback
          echo "Host ${{ secrets.VPSHOST }}" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
        else
          echo "Error: VPSHOST secret is not set"
          exit 1
        fi

    - name: Deploy to VPS
      run: |
        make deploy
      working-directory: shortener
      env:
        SSHPASS: ${{ secrets.SSHPASS }}

    - name: Verify deployment
      run: |
        curl -sSf -H "Host: url.govno2.cloud" http://${{ secrets.VPSHOST }}/health

