name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Start test services
      run: docker compose up -d db
      working-directory: shortener

    - name: Wait for database
      run: |
        timeout 30s bash -c 'until docker compose exec db pg_isready -U postgres; do sleep 1; done'
      working-directory: shortener

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod download
      working-directory: shortener

    - name: Run tests
      run: make test
      working-directory: shortener
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/url_shortener?sslmode=disable

    - name: Run lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: shortener

    - name: Stop test services
      if: always()
      run: docker compose down
      working-directory: shortener

  build:
    name: Build and Push Image
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository_owner }}/url-shortener:latest .
      working-directory: shortener

    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository_owner }}/url-shortener:latest
      working-directory: shortener

