name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Copy deployment files
      run: |
        scp -i ~/.ssh/id_rsa docker-compose.yml url-shortener@${{ secrets.VPS_HOST }}:~/url-shortener/
        scp -i ~/.ssh/id_rsa docker-compose.prod.yml url-shortener@${{ secrets.VPS_HOST }}:~/url-shortener/

    - name: Deploy to VPS
      run: |
        ssh -i ~/.ssh/id_rsa url-shortener@${{ secrets.VPS_HOST }} "cd ~/url-shortener && docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull && docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d"

    - name: Verify deployment
      run: |
        ssh -i ~/.ssh/id_rsa url-shortener@${{ secrets.VPS_HOST }} "curl -s http://localhost:8080 | grep -q 'URL Shortener'"

    - name: Cleanup old containers
      run: |
        ssh -i ~/.ssh/id_rsa url-shortener@${{ secrets.VPS_HOST }} "docker system prune -f"
